//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayapadaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int UserId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        [Required(AllowEmptyStrings =false, ErrorMessage = "Required username")]
        public string Username { get; set; }

        [Required(AllowEmptyStrings =false, ErrorMessage ="Required password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string Address { get; set; }
    }
}
